services:
  - type: web
    name: proyectoaula-tendencias
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi:application --log-file -
